### ISSUE TITLE
[meta] Code Review Bot development 2024 by Teklia

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/code-review#2273]
```[tasklist]
- [ ] https://github.com/mozilla/code-review/issues/2194
- [ ] https://github.com/mozilla/code-review/issues/2260
- [ ] https://github.com/mozilla/code-review/issues/2124
- [ ] https://github.com/mozilla/code-review/issues/2259
- [ ] https://github.com/mozilla/code-review/issues/2192
- [ ] https://github.com/mozilla/code-review/issues/1592
- [ ] https://github.com/mozilla/code-review/issues/1957
- [ ] https://github.com/mozilla/code-review/issues/1956
- [ ] https://github.com/mozilla/code-review/issues/1119
- [ ] https://github.com/mozilla/code-review/issues/1539
- [ ] https://github.com/mozilla/code-review/issues/1696
- [ ] https://github.com/mozilla/code-review/issues/1406
- [ ] https://github.com/mozilla/code-review/issues/377
- [ ] https://github.com/mozilla/code-review/issues/2042
- [ ] https://github.com/mozilla/code-review/issues/180
- [ ] https://github.com/mozilla/code-review/issues/278
- [ ] https://github.com/mozilla/code-review/issues/981
- [ ] https://github.com/mozilla/code-review/issues/945
- [ ] https://github.com/mozilla/code-review/issues/468
- [ ] https://github.com/mozilla/code-review/issues/1577
- [ ] https://github.com/mozilla/code-review/issues/1575
```

@La0 @marco-c
