### ISSUE TITLE
Code review bot cleanup

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#28]
- [x] Remove local analyzers, deps and deprecated code (#2071)
- [x] Need to merge RemoteWorkflow in Workflow, and put the resulting class in a single file (#2081)
- [x] Need to merge PhabricatorRevision in Revision (#1899)
- [x] Need to remove Coverity options/secret and only keep the full stack option (#2082)
- [x] Coverity has a lot less unit tests, as they were only around the local analyzer (#2079 and #2080)
- [x] Simplify `CoverityIssue.__init__` as only one of two format is now supported (#2083)
- [x] Move clang checks validation in `./mach static-analysis check` [Bug 1550516](https://bugzilla.mozilla.org/show_bug.cgi?id=1550516) 
- [x] Add 3rd party checks on ~mozlint~ & `./mach static-analysis check` [Bug 1550516](https://bugzilla.mozilla.org/show_bug.cgi?id=1550517)
